 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet run --project .\src\MKasperczyk.Reservation.Api\MKasperczyk.Reservation.Api.csproj
